/**
 * GENERATED by scripts/gen-visuals.mjs — do not edit. The pictures actually on
 * disk under static/visuals, as `lens/<key>.jpg` / `opt/<qid>-<key>.jpg`.
 * `visuals.ts` answers from this list, never from the question set alone, so a
 * picture that was never generated is absent from the app rather than a 404.
 * Regenerate: node scripts/gen-visuals.mjs --manifest-only
 */
export const VISUAL_FILES: readonly string[] = [
	'lens/arcology.jpg',
	'lens/broadacre-city.jpg',
	'lens/garden-city.jpg',
	'lens/neo-seoul.jpg',
	'lens/pragmatist-retrofit.jpg',
	'lens/retrofuturism.jpg',
	'lens/solarpunk.jpg',
	'opt/q10-adapts-as-needs-change.jpg',
	'opt/q10-knows-when-to-step-back.jpg',
	'opt/q10-protects-attention.jpg',
	'opt/q10-supports-judgement.jpg',
	'opt/q11-alive.jpg',
	'opt/q11-calm.jpg',
	'opt/q11-effortless.jpg',
	'opt/q11-electric.jpg',
	'opt/q11-focused.jpg',
	'opt/q11-playful.jpg',
	'opt/q11-sacred.jpg',
	'opt/q11-yours.jpg',
	'opt/q2-deep-low-lit.jpg',
	'opt/q2-raw-elemental.jpg',
	'opt/q2-undersea.jpg',
	'opt/q8-deliberate-pockets.jpg',
	'opt/q8-sparse-inside-abundant-outside.jpg'
];
