#!/usr/bin/env node
/**
 * GEN-VISUALS — generates one lens image per future (src/lib/game/futures.ts)
 * and one option image per non-open, non-wildcard option (src/lib/game/questions.ts),
 * via fal's nano-banana-2 queue API (same model + endpoint shape as
 * src/lib/server/fal.ts: submit -> poll status -> fetch result).
 *
 * Idempotent: any output file that already exists on disk is skipped, so a
 * partial run (budget cutoff, a flaky call) can be safely re-run.
 *
 * Run it as `node --no-network-family-autoselection scripts/gen-visuals.mjs`.
 * This Mac's resolver hands Node a synthesised NAT64 address for `fal.run`
 * alongside the real A record, Node's happy-eyeballs tries it, and the 250 ms
 * attempt timer fires as `fetch failed` / `ETIMEDOUT` in ~270 ms — every call,
 * indistinguishable from fal being down, while `curl` to the same host works.
 * Measured 2026-09-21; the flag made six dead jobs succeed on the next run.
 *
 * FAL_KEY is read from a .dev.vars file (path given by --keyfile, default
 * the sibling _deploy checkout) with a two-line reader — no dotenv
 * dependency, no logging of the key at any point.
 *
 * Every run (and `--manifest-only`, which needs no key) rewrites
 * `src/lib/game/visuals-manifest.ts` — the basenames actually on disk under
 * `static/visuals/{lens,opt}` — which is what `visuals.ts` answers from.
 * A picture that was never generated is then simply absent from the app,
 * never an <img> with a 404 source.
 *
 * Usage:
 *   node scripts/gen-visuals.mjs [--only=lens|opt] [--limit=N] [--dry-run] [--manifest-only]
 */
import { register } from 'node:module';
import { writeFile, mkdir, stat } from 'node:fs/promises';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
register('./ts-ext-loader.mjs', import.meta.url);

const ROOT = join(__dirname, '..');
const KEYFILE =
	process.env.FAL_KEYFILE ?? '/Users/rick.d/Developer/zyetaone/_deploy/z-interact-v4/.dev.vars';

/** Two-line .env-style reader: just enough to pull FAL_KEY=... out of a
 *  dotenv-shaped file. Never prints the value, never keeps it beyond the
 *  process env for this run. */
function readFalKey(path) {
	const line = readFileSync(path, 'utf8')
		.split('\n')
		.find((l) => l.startsWith('FAL_KEY='));
	if (!line) throw new Error(`FAL_KEY not found in ${path}`);
	return line.slice('FAL_KEY='.length).trim();
}

const MODEL = 'fal-ai/nano-banana-2';
const QUEUE_URL = `https://queue.fal.run/${MODEL}`;

const args = new Map(
	process.argv.slice(2).map((a) => {
		const [k, v] = a.replace(/^--/, '').split('=');
		return [k, v ?? true];
	})
);
const ONLY = args.get('only'); // 'lens' | 'opt' | undefined
const LIMIT = args.get('limit') ? Number(args.get('limit')) : Infinity;
const DRY_RUN = Boolean(args.get('dry-run'));
const MANIFEST_ONLY = Boolean(args.get('manifest-only'));
const BUDGET = 70;

// --- manifest ------------------------------------------------------------------

/** Rewrites src/lib/game/visuals-manifest.ts from what is on disk right now. */
async function writeManifest() {
	const list = (dir) =>
		existsSync(join(ROOT, 'static/visuals', dir))
			? readdirSync(join(ROOT, 'static/visuals', dir))
					.filter((f) => f.endsWith('.jpg'))
					.sort()
					.map((f) => `${dir}/${f}`)
			: [];
	const files = [...list('lens'), ...list('opt')];
	const body =
		`/**\n * GENERATED by scripts/gen-visuals.mjs — do not edit. The pictures actually on\n` +
		` * disk under static/visuals, as \`lens/<key>.jpg\` / \`opt/<qid>-<key>.jpg\`.\n` +
		` * \`visuals.ts\` answers from this list, never from the question set alone, so a\n` +
		` * picture that was never generated is absent from the app rather than a 404.\n` +
		` * Regenerate: node scripts/gen-visuals.mjs --manifest-only\n */\n` +
		`export const VISUAL_FILES: readonly string[] = [\n` +
		files.map((f) => `\t'${f}'`).join(',\n') +
		`\n];\n`;
	await writeFile(join(ROOT, 'src/lib/game/visuals-manifest.ts'), body);
	console.log(`manifest: ${files.length} file(s) -> src/lib/game/visuals-manifest.ts`);
}

if (MANIFEST_ONLY) {
	await writeManifest();
	process.exit(0);
}

const FAL_KEY = readFalKey(KEYFILE);

const { FUTURES, HOUSE_NEGATIVE } = await import('../src/lib/game/futures.ts');
const { QUESTIONS } = await import('../src/lib/game/questions.ts');

// --- job list ----------------------------------------------------------------

/** One `[key, promptFragment, negative]` job per future's cues, written per
 *  futures.md §2's per-future evidence (five cues each, folded into the
 *  moodLine already in futures.ts — see the report for the cue list). */
/** Folded into every lens prompt and negative after solarpunk.jpg and
 *  retrofuturism.jpg came back with a dozen sharp, identifiable people —
 *  a populated stock-photo scene rather than the reference material's
 *  anonymous-figures convention (futures.md §3's "no personas" brief). */
const NO_PEOPLE_POSITIVE = 'no visible human figures; at most distant, blurred silhouettes; no faces';
const NO_PEOPLE_NEGATIVE = 'crowds, people in focus, sharp faces, posed figures, identifiable persons';

/**
 * THE SELECTION ART WAS DIM, AND IT WAS NOT THE FUTURE.
 *
 * Measured on the fifty-three option thumbnails as first generated: median
 * luminance 47 of 255, with thirty-eight below 70, against 113 for the wall
 * renders. And the pictures themselves were medieval — stone arches, castle
 * corridors, a Victorian panelled door — or else a present-day office.
 *
 * Both came from one line. The option frame was "a single architectural
 * detail, close, moody, photoreal", which asks for dimness in so many words
 * and never mentions the year, so the model had nothing pulling it forward
 * and a word pulling it dark. The lens pictures had their own version of
 * the same problem: they were composed from `moodLine`, the pre-recipe-v2
 * mood paragraph, which for the dense and lit city literally reads "Night
 * ... no daylight anywhere". That is the lens-by-day problem the render
 * prompts fixed weeks ago and the selection art never received.
 *
 * So the selection art now uses the same three ideas the renders use — a
 * stated year, an exposure, and a lens described by its style rather than
 * its weather — and the negatives name the two drifts that actually
 * happened rather than a generic list.
 */
const EXPOSURE = 'bright overall exposure, daylight filling the volume, open shadows';
const NOT_DIM = 'underexposed, murky, crushed blacks, gloom';
/** The period drift, named from what came back: it really did draw castles. */
const NOT_PERIOD =
	'medieval, gothic arches, castle, crypt, carved stone, stone vaulting, Victorian panelling, period drama, ruins';
/** The other direction: today's office is not the future either. */
const NOT_TODAY = 'present-day office, 2020s office furniture, cubicles, drop ceiling, fluorescent panels';

function lensJobs() {
	return FUTURES.map((f) => ({
		kind: 'lens',
		outPath: join(ROOT, 'static/visuals/lens', `${f.key}.jpg`),
		// `styleDna` + `worldOutside` + `insideCue`, NOT `moodLine`. Those three
		// are what recipe v2 split out precisely so a lens keeps its identity
		// at any hour; `moodLine` still carries the night and the weather.
		prompt: `A workplace of 2040 seen from inside, ${f.styleDna}. ${f.worldOutside}. ${f.insideCue}. Photoreal film still, ${EXPOSURE}. ${NO_PEOPLE_POSITIVE}. Avoid: ${f.negativeFragment}, ${HOUSE_NEGATIVE}, ${NO_PEOPLE_NEGATIVE}, ${NOT_DIM}, ${NOT_PERIOD}, ${NOT_TODAY}.`,
		aspect_ratio: '4:3',
		resolution: '1K'
	}));
}

function optionJobs() {
	const jobs = [];
	for (const q of QUESTIONS) {
		for (const o of q.options) {
			if (o.open) continue; // free-text options: no fixed visual to render
			jobs.push({
				kind: 'opt',
				outPath: join(ROOT, 'static/visuals/opt', `${q.id}-${o.key}.jpg`),
				prompt:
					q.layer === 'feel'
						? // Feel words are light, not objects: frame them as a whole room.
							`A film still inside one workplace of 2040, anamorphic, photoreal, its whole mood: ${o.promptFragment}. ${EXPOSURE}. ${NO_PEOPLE_POSITIVE}. Avoid: ${HOUSE_NEGATIVE}, ${NO_PEOPLE_NEGATIVE}, ${NOT_DIM}, ${NOT_PERIOD}, ${NOT_TODAY}.`
						: // Everything else: the thing the option names, INSIDE a workplace of
							// 2040 and lit. "A single architectural detail, close, moody" is what
							// produced the castle corridors and the dim brown thumbnails.
							`A film still inside one workplace of 2040, photoreal: ${o.promptFragment}. ${EXPOSURE}. ${NO_PEOPLE_POSITIVE}. Avoid: ${HOUSE_NEGATIVE}, ${NO_PEOPLE_NEGATIVE}, ${NOT_DIM}, ${NOT_PERIOD}, ${NOT_TODAY}.`,
				aspect_ratio: '1:1',
				resolution: '0.5K'
			});
		}
	}
	return jobs;
}

let jobs = [...(ONLY === 'opt' ? [] : lensJobs()), ...(ONLY === 'lens' ? [] : optionJobs())];
jobs = jobs.filter((j) => !existsSync(j.outPath));
if (jobs.length > BUDGET) {
	console.log(`${jobs.length} pending jobs exceeds budget of ${BUDGET}; trimming to ${BUDGET}.`);
	jobs = jobs.slice(0, BUDGET);
}
jobs = jobs.slice(0, LIMIT);

console.log(`${jobs.length} image(s) to generate (skipping files that already exist).`);
if (DRY_RUN) {
	for (const j of jobs) console.log(`[dry-run] ${j.kind} -> ${j.outPath}`);
	process.exit(0);
}

// --- fal queue calls -----------------------------------------------------------

async function submit(job) {
	const res = await fetch(QUEUE_URL, {
		method: 'POST',
		headers: { Authorization: `Key ${FAL_KEY}`, 'Content-Type': 'application/json' },
		body: JSON.stringify({
			prompt: job.prompt,
			aspect_ratio: job.aspect_ratio,
			resolution: job.resolution,
			output_format: 'jpeg',
			num_images: 1
		})
	});
	if (!res.ok) throw new Error(`submit ${res.status}: ${await res.text().catch(() => '')}`);
	const body = await res.json();
	return body.request_id;
}

async function pollUntilDone(requestId, { intervalMs = 3000, timeoutMs = 180_000 } = {}) {
	const start = Date.now();
	for (;;) {
		const res = await fetch(`${QUEUE_URL}/requests/${requestId}/status`, {
			headers: { Authorization: `Key ${FAL_KEY}` }
		});
		if (!res.ok) throw new Error(`status ${res.status}: ${await res.text().catch(() => '')}`);
		const body = await res.json();
		if (body.status === 'COMPLETED') return;
		if (Date.now() - start > timeoutMs) throw new Error(`timed out waiting on ${requestId}`);
		await new Promise((r) => setTimeout(r, intervalMs));
	}
}

async function fetchResult(requestId) {
	const res = await fetch(`${QUEUE_URL}/requests/${requestId}`, {
		headers: { Authorization: `Key ${FAL_KEY}` }
	});
	if (!res.ok) throw new Error(`result ${res.status}: ${await res.text().catch(() => '')}`);
	const body = await res.json();
	const url = body.images?.[0]?.url;
	if (!url) throw new Error('no image in result');
	return url;
}

async function runJob(job) {
	const requestId = await submit(job);
	await pollUntilDone(requestId);
	const imageUrl = await fetchResult(requestId);
	const imgRes = await fetch(imageUrl);
	if (!imgRes.ok) throw new Error(`download ${imgRes.status}`);
	const buf = Buffer.from(await imgRes.arrayBuffer());
	await mkdir(dirname(job.outPath), { recursive: true });
	await writeFile(job.outPath, buf);
	return buf.length;
}

// --- run, with a two-strikes-and-stop rule per the task's error budget ------

let consecutiveErrors = 0;
let done = 0;
const oversized = [];

/**
 * `fetch failed` — a dropped connection, not an HTTP status — arrives from fal
 * often enough that a single one used to end a whole run: two in a row tripped
 * the budget guard, and a 59-image regeneration needed four manual restarts.
 * Three attempts with a widening pause turns that into a pause. A real refusal
 * (a 4xx from submit, a locked account) still throws on the last attempt and
 * still counts toward the two-strike guard, which is the thing worth stopping
 * for. ponytail: fixed backoff, no jitter — one client, nothing to stampede.
 */
async function runJobWithRetries(job, attempts = 3) {
	for (let i = 1; ; i++) {
		try {
			return await runJob(job);
		} catch (err) {
			if (i >= attempts) throw err;
			process.stdout.write(`(${err.message}, retry ${i}) `);
			await new Promise((r) => setTimeout(r, i * 5000));
		}
	}
}

for (const job of jobs) {
	process.stdout.write(`${job.kind} ${job.outPath.replace(ROOT + '/', '')} ... `);
	try {
		const bytes = await runJobWithRetries(job);
		consecutiveErrors = 0;
		done++;
		const kb = (bytes / 1024).toFixed(0);
		console.log(`ok (${kb} KB)`);
		const limitKb = job.kind === 'lens' ? 400 : 250;
		if (bytes / 1024 > limitKb) oversized.push({ path: job.outPath, kb });
	} catch (err) {
		consecutiveErrors++;
		console.log(`FAILED: ${err.message}`);
		if (consecutiveErrors >= 2) {
			console.error('Two consecutive failures — stopping per budget guard.');
			break;
		}
	}
}

console.log(`\nGenerated ${done}/${jobs.length} image(s).`);
await writeManifest();
if (oversized.length) {
	console.log('Over target size budget:');
	for (const o of oversized) console.log(`  ${o.path.replace(ROOT + '/', '')} — ${o.kb} KB`);
}
